package com.p4r4d0x.edmgenreclassifier.datasource.repository.impl

import com.p4r4d0x.edmgenreclassifier.datasource.repository.ProfileInfoRepository

class ProfileInfoRepositoryImpl : ProfileInfoRepository